//Atividade realizada em Java

//Crie uma situação em que ocorra uma exceção dentro de um código. Utilize try/catch para realizar a captura e tratamento dessa exceção. 

public class CarrinhoDeCompras {
    private double total;
    private Produto[] produtos = new Produto[10];
    private int contador = 0;

    public void adiciona(Produto produto) {
        System.out.println("Adicionando " + produto);
        this.produtos[contador++] = produto;
        this.total += produto.getValor();
    }

    public double getTotal() {
        return total;
    }

    for(

    int i = 0;i<=produtos.length;i++)
    {
        try {
            Produto produto = produtos[i];
            if (produto != null) {
                System.out.println(produto.getValor());
            }
        } catch (ArrayIndexOutOfBoundsException e) {
            System.out.println("Deu exception no índice: " + i);
        }
    }System.out.println("Fui executado!");
}
